'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace BSIT
    Partial Public Class AddUsers
        Inherits System.Web.UI.Page

        Protected WithEvents form1 As System.Web.UI.HtmlControls.HtmlForm
        Protected WithEvents txtUsername As System.Web.UI.WebControls.TextBox
        Protected WithEvents rfvUsername As System.Web.UI.WebControls.RequiredFieldValidator
        Protected WithEvents txtFullName As System.Web.UI.WebControls.TextBox
        Protected WithEvents rfvFullName As System.Web.UI.WebControls.RequiredFieldValidator
        Protected WithEvents txtEmail As System.Web.UI.WebControls.TextBox
        Protected WithEvents rfvEmail As System.Web.UI.WebControls.RequiredFieldValidator
        Protected WithEvents revEmail As System.Web.UI.WebControls.RegularExpressionValidator
        Protected WithEvents txtPassword As System.Web.UI.WebControls.TextBox
        Protected WithEvents rfvPassword As System.Web.UI.WebControls.RequiredFieldValidator
        Protected WithEvents txtConfirmPassword As System.Web.UI.WebControls.TextBox
        Protected WithEvents rfvConfirmPassword As System.Web.UI.WebControls.RequiredFieldValidator
        Protected WithEvents cvPassword As System.Web.UI.WebControls.CompareValidator
        Protected WithEvents ddlUserType As System.Web.UI.WebControls.DropDownList
        Protected WithEvents rfvUserType As System.Web.UI.WebControls.RequiredFieldValidator
        Protected WithEvents chkActive As System.Web.UI.WebControls.CheckBox
        Protected WithEvents lblMessage As System.Web.UI.WebControls.Label
        Protected WithEvents btnSave As System.Web.UI.WebControls.Button
        Protected WithEvents btnCancel As System.Web.UI.WebControls.Button
    End Class
End Namespace
