'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace BSIT
    Partial Public Class ArchivePosts

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As System.Web.UI.HtmlControls.HtmlForm
        Protected WithEvents ScriptManager1 As System.Web.UI.ScriptManager
        Protected WithEvents btnReturnToManage As System.Web.UI.WebControls.Button
        Protected WithEvents txtSearch As System.Web.UI.WebControls.TextBox
        Protected WithEvents btnSearch As System.Web.UI.WebControls.Button
        Protected WithEvents ddlArchiveDate As System.Web.UI.WebControls.DropDownList
        Protected WithEvents gvArchivedPosts As System.Web.UI.WebControls.GridView
        Protected WithEvents pnlNoResults As System.Web.UI.WebControls.Panel
        Protected WithEvents btnBackToManage As System.Web.UI.WebControls.Button
    End Class
End Namespace
